config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    get 'transcriber', to: 'static_pages#transcriber'
    get 'caption_downloader', to: 'static_pages#caption_downloader'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'
    get '/preview', to: 'static_pages#preview'
    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'


    # sitemap
    get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/diqtsub_sitemaps/sitemap.xml.gz')
    get 'ads.txt', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/ads.txt')

    resources :subtitles do
      collection do
        get  :select_captions
        post :download_caption
        get  :form_to_transcribe
        get  :checkout
        get  :transcribe
      end
    end

    #resources :wordnet do
    #  collection do
    #    get :home, :en_en_dict, :ja_ja_dict
    #  end
    #end
    #
    # 記事
    resources :articles do
      member do
        get :new_translation
        get :edit_title
        patch :update_title
        get :cancel
        get :translation_select
        # タグの編集
        get   :edit_tags
        patch :update_tags
        # 字幕のダウンロード
        get :caption_downloader
        get :download_caption
        # 翻訳
        post :batch_translation
        post :translate_in_bulk
        # 翻訳に課金する場合は以下
        get :checkout_translation
        get :success_translation
        # Youtubeから原文と翻訳をインポートする
        post :passage_importer
        post :import_passages
        post :translation_importer
        post :import_translations
        # SRTから原文と翻訳をインポートする。
        post :passage_file_importer
        post :import_passage_file
        post :translation_file_importer
        post :import_translation_file
      end
      collection do
        get  :new_video
        post :create_video
      end
    end


    resources :passages do
      member do
        # get :histories
      end
      collection do
        get :cancel
      end
    end

    # 翻訳 / 記事＆原文＆翻訳の投稿は実験のためにログイン不要にしても良い。問題が起きたら対処する。
    resources :translations do
      collection do
        get  :new_title
        post :create_title
        get :cancel
      end
      member do
        get    :edit_title
        patch  :update_title
        delete :destroy_title
      end
    end

    resources :tags, only: [:index, :show, :destroy] do
      collection do
        get :article_tags
      end
      member do
        get :articles
      end
    end

    resources :words, only: [:index] do
      collection do
        get :click_search
      end
    end


  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :extract_user_language

  def home
    @articles_count = Article.all.size
    @navbar_displayed = true
    @articles = Article.all.order(created_at: :desc).page(params[:page]).per(12)
  end
  
  def transcriber
    @navbar_displayed = true
    @breadcrumb_hash = { t('static_pages.home') => root_path,
                         t('subtitles.transcribe_videos_on_youtube') => '' }
  end

  def caption_downloader
    @navbar_displayed = true
    @breadcrumb_hash = { t('static_pages.home') => root_path,
                         t('subtitles.download_captions_on_youtube') => '' }
  end

  def preview
    @text = params[:text]
    @lang_number = params[:lang_number].to_i
  end


  private
  
  def extract_user_language
    available = %w[ja en]
    @user_language = http_accept_language.preferred_language_from(available)
  end

end

app/views/static_pages/_preview_modal.html.erb
<div class="badge-modal-wrapper" id="text-preview-modal">

  <div class="overlay close-text-preview-modal">
    <div class="close-btn">
      <i class="fal fa-times"></i>
    </div>
  </div>


  <div class="modal-booqs" id="text-preview">

    <h3 class="text-center text-success font-weight-bold mt-3 mb-4"><%= t('articles.text_preview') %></h3>

    <div class="card text-left mb-5">
      <div class="card-body">
        <% if @text.present? %>
          <%= render 'shared/text_with_dict', text: @text, lang_number: @lang_number %>
        <% else %>
          <p><%= t('articles.there_is_no_text') %></p>
        <% end %>

        <% if @lang_number != 0 %>
          <p class="mt-4 text-secondary"><%= t 'lang.language_setting' %>
            ：<b><%= lang_number_to_lang_name @lang_number %></b></p>
        <% else %>
          <p class="mt-4 text-secondary"><%= t 'lang.language_setting' %>
            ：<b class="text-danger"><%= t('articles.undefined_lang_number') %></b></p>
        <% end %>
      </div>
    </div>





    <h3 class="text-left mt-5 mb-4 text-success font-weight-bold"><%= t('articles.booqs_notation') %></h3>

    <% text_1 = "I’d like to move on if I may." %>
    <div class="text-left">
      <p class="text-secondary"><%= t('articles.notation_exp_1_html') %></p>
      <div class="card w-100 mb-5">
        <div class="card-header">
          <%= t('articles.notation_example') %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= render 'shared/text_with_dict', text: text_1, lang_number: 21 %></li>
        </ul>
      </div>


      <p class="text-secondary"><%= t('articles.notation_exp_2_html') %></p>

      <% text_2 = "I’d like to [[move on]] [[if I may]]." %>
      <div class="card w-100 mb-5">
        <div class="card-header">
          <%= t('articles.notation_example') %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= text_2 %></li>
          <li class="list-group-item"><%= render 'shared/text_with_dict', text: text_2, lang_number: 21 %></li>
        </ul>
      </div>

      <p class="text-secondary"><%= t('articles.notation_exp_3_html') %></p>
      <% text_3 = "[[I’d like to|would like to]] move on if I may." %>
      <div class="card w-100 mb-5">
        <div class="card-header">
          <%= t('articles.notation_example') %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= text_3 %></li>
          <li class="list-group-item"><%= render 'shared/text_with_dict', text: text_3, lang_number: 21 %></li>
        </ul>
      </div>




    </div>


  </div>
</div>

app/views/static_pages/caption_downloader.html.erb
<!-- ?ref=starsaas によるホームページが重複してindexされてる問題の解決　-->
<!-- localize: https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=ja -->
<% set_meta_tags title: t('subtitles.download_captions_on_youtube'),
                 description: t('subtitles.description'),
                 canonical: caption_downloader_url(locale: @locale),
                 twitter: { card: 'summary_large_image' },
                 alternate: { "en" => caption_downloader_url(locale: 'en'),
                              "ja" => caption_downloader_url(locale: 'ja') } %>



<%= render 'layouts/recommendation_to_switch_locale' %>

<div class="container bg-white pt-5 pb-5 my-5">
  <div class="row justify-content-md-center">
    <div class="col col-lg-10">

      <ul class="nav nav-tabs mb-5">
        <li class="nav-item">
          <a class="nav-link active" href=""><%= t('layouts.download_caption') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-success" href="<%= transcriber_path %>"> <%= t('layouts.transcribe_video') %></a>
        </li>

      </ul>

      <h1 class="font-weight-bold mb-4"><%= t 'subtitles.download_captions_on_youtube' %></h1>


      <p><%= t 'subtitles.description' %></p>

      <%= form_with url: select_captions_subtitles_url, method: :get do |f| %>

        <div class="input-group my-5">
          <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroupPrepend">URL</span>
          </div>
          <%= f.text_field :url, class: 'form-control', placeholder: "#{t 'subtitles.placeholder'}" %>
          <div class="invalid-feedback" id="invalid-feedback"></div>
        </div>

        <%= f.submit 'OK', class: 'btn btn-solid w-100 mb-4 font-weight-bold main-loading-show-btn' %>

      <% end %>

    </div>
  </div>
</div>


<%= render 'layouts/breadcrumb', items_hash: @breadcrumb_hash %>

app/views/static_pages/home.html.erb
<% set_meta_tags title: t('subtitles.download_captions_on_youtube'),
                 description: t('subtitles.description'),
                 canonical: root_url(locale: @locale),
                 twitter: {card: 'summary_large_image'},
                 alternate: {"en" => root_url(locale: 'en'),
                             "ja" => root_url(locale: 'ja')} %>





<div class="container bg-white pt-5 pb-5 my-5">
  <div class="row justify-content-md-center">
    <div class="col col-lg-10">
      <h1 class="font-weight-bold mb-4"><%= title t 'articles.articles' %></h1>

      <% if @articles_count > 12 %>
        <div id="infinite-scroll">
          <div class="append-content">
            <%= render 'articles/cards', articles: @articles %>
          </div>
          <%= render "shared/infinite_scroll_normal", contents: @articles %>
        </div>
      <% else %>
        <%= render 'articles/cards', articles: @articles %>
      <% end %>


    </div>
  </div>
</div>

app/views/static_pages/preview.js.erb
$('.loading').addClass('is-hide');
$("#main").append("<%= escape_javascript(render('static_pages/preview_modal') ) %>");
//$("#text-preview").animate({'top': '56px'},400, 'easeOutExpo');

$('body').addClass('overflow-hidden');

// 閉じる処理
$(document).on("click", ".close-text-preview-modal", function () {
    $('#text-preview-modal').fadeOut().queue(function() {
        $("#text-preview-modal").remove();
    });
    $('body').removeClass('overflow-hidden');
});

app/views/static_pages/transcriber.html.erb
<!-- ?ref=starsaas によるホームページが重複してindexされてる問題の解決　-->
<!-- localize: https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=ja -->
<% set_meta_tags title: t('subtitles.transcribe_videos_on_youtube'),
                 description: t('subtitles.description_about_transcriber'),
                 canonical: transcriber_url(locale: @locale),
                 twitter: { card: 'summary_large_image' },
                 alternate: { "en" => transcriber_url(locale: 'en'),
                              "ja" => transcriber_url(locale: 'ja')} %>


<%= render 'layouts/recommendation_to_switch_locale' %>

<div class="container bg-white pt-5 pb-5 my-5">

  <div class="row justify-content-md-center mb-5">
    <div class="col col-lg-10">

      <ul class="nav nav-tabs mb-5">
        <li class="nav-item">
          <a class="nav-link text-success" href="<%= caption_downloader_path %>"><%= t('layouts.download_caption') %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="#"> <%= t('layouts.transcribe_video') %></a>
        </li>

      </ul>


      <h1 class="font-weight-bold mb-4"><%= t 'subtitles.transcribe_videos_on_youtube' %></h1>


      <p><%= t 'subtitles.description_about_transcriber' %></p>


      <%= form_with url: form_to_transcribe_subtitles_url, method: :get do |f| %>

        <div class="input-group my-5">
          <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroupPrepend">URL</span>
          </div>
          <%= f.text_field :url, class: 'form-control', placeholder: t('subtitles.placeholder_on_transcriber') %>
          <div class="invalid-feedback" id="invalid-feedback"></div>
        </div>



        <%= f.submit 'OK', class: 'btn btn-solid w-100 mb-4 main-loading-show-btn' %>

      <% end %>

    </div>
  </div>
</div>

<%= render 'layouts/breadcrumb', items_hash: @breadcrumb_hash %>