config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    get 'transcriber', to: 'static_pages#transcriber'
    get 'caption_downloader', to: 'static_pages#caption_downloader'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'
    get '/preview', to: 'static_pages#preview'
    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'


    # sitemap
    get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/diqtsub_sitemaps/sitemap.xml.gz')
    get 'ads.txt', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/ads.txt')

    resources :subtitles do
      collection do
        get  :select_captions
        post :download_caption
        get  :form_to_transcribe
        get  :checkout
        get  :transcribe
      end
    end

    #resources :wordnet do
    #  collection do
    #    get :home, :en_en_dict, :ja_ja_dict
    #  end
    #end
    #
    # 記事
    resources :articles do
      member do
        get :new_translation
        get :edit_title
        patch :update_title
        get :cancel
        get :translation_select
        # タグの編集
        get   :edit_tags
        patch :update_tags
        # 字幕のダウンロード
        get :caption_downloader
        get :download_caption
        # 翻訳
        post :batch_translation
        post :translate_in_bulk
        # 翻訳に課金する場合は以下
        get :checkout_translation
        get :success_translation
        # Youtubeから原文と翻訳をインポートする
        post :passage_importer
        post :import_passages
        post :translation_importer
        post :import_translations
        # SRTから原文と翻訳をインポートする。
        post :passage_file_importer
        post :import_passage_file
        post :translation_file_importer
        post :import_translation_file
      end
      collection do
        get  :new_video
        post :create_video
      end
    end


    resources :passages do
      member do
        # get :histories
      end
      collection do
        get :cancel
      end
    end

    # 翻訳 / 記事＆原文＆翻訳の投稿は実験のためにログイン不要にしても良い。問題が起きたら対処する。
    resources :translations do
      collection do
        get  :new_title
        post :create_title
        get :cancel
      end
      member do
        get    :edit_title
        patch  :update_title
        delete :destroy_title
      end
    end

    resources :tags, only: [:index, :show, :destroy] do
      collection do
        get :article_tags
      end
      member do
        get :articles
      end
    end

    resources :words, only: [:index] do
      collection do
        get :click_search
      end
    end


  end
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :article
  belongs_to :passage, optional: true

  validates :text, presence: true
  validate :lang_number_set
  validate :lang_number_cannot_be_duplicated


  def lang_number_set
    errors.add(:lang_number, I18n.t('articles.lang_number_error')) if lang_number.blank?
  end

  def lang_number_cannot_be_duplicated
    errors.add(:lang_number, I18n.t('translations.lang_number_cannot_be_duplicated')) if lang_number_unique?
  end

  def lang_number_unique?
    # createではなく、updateの場合、自分が含まれてしまうことで更新できなくなる恐れがあるため、最後に t != self で確認する。
    if passage_targeted? && (t = passage.translations.find_by(lang_number: lang_number)) && t != self
      true
    elsif title_targeted? && (a = article.title_translations.find_by(lang_number: lang_number)) && a != self
      true
    else
      false
    end
  end

  def passage_targeted?
    passage.present?
  end

  def title_targeted?
    passage.blank?
  end

  def set_lang_number
    self.lang_number = Lang.return_lang_number(text) if lang_number.nil?
  end

  def separate_text
    return if Lang.text_to_be_separated?(lang_number) == false

    separated_text = Lang.separate_text(text, lang_number)
    self.text = separated_text if separated_text.present?
  end

  # データをsaveするまでに必要な一連の処理をまとめたメソッド / Method bunching processes that record needs until saving.
  def set_attributes
    set_lang_number
    self.title = true if passage_id.blank?
  end

  def lang_code
    Lang.convert_number_to_code(lang_number)
  end

  # wikiリンクを削除したplainなtextを返す
  # TODO: application_helperのsanitize_links(text)に置き換える。
  def plain_text
    # .*?で最短マッチ。 [[]]を持っているテキストを分割して抽出
    # shared/line_with_dictと同じ処理
    text_array = text.split(/(\[{2}.*?\]{2})/)
    plain_text_array = text_array.map do |text|
      if text.match?(/\[{2}.+\]{2}/)
        text.delete("[[,]]").split(/\|/, 2).first
      else
        text
      end
    end

    plain_text_array.join
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController


  def new
    @passage = Passage.find(params[:passage_id])
    @article = @passage.article
    @editor_token = SecureRandom.uuid
    @lang_code_of_translation = params[:lang_code_of_translation]
    @translation = @passage.translations.build
    source = Lang.convert_number_to_code(@passage.lang_number)
    # target（翻訳結果）がセットされていない場合は、ユーザーの母語を翻訳結果に指定する。
    target = @lang_code_of_translation
    @translation_text = Lang.google_translate(source, target, @passage.text) if source.present? && target.present?
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end


  def create
    @translation = Translation.new(translation_params)
    @passage = @translation.passage
    @article = @passage.article
    @translation.article = @article
    @translation.set_attributes
    @editor_token = params[:editor_token]
    @lang_code_of_translation = Lang.convert_number_to_code(@translation.lang_number)
    @valid = @translation.valid?
    return if @valid == false

    # @translation.separate_text if params[:separateText].present?
    @translation.save
    @message = t('translations.created_message')
    ActionCable.server.broadcast 'translation_modification_channel',
                                 html: render(partial: 'passages/translation',
                                              locals: {translation: @translation, passage: @passage}),
                                 translation: @translation,
                                 lang_code: @lang_code_of_translation,
                                 passage: @passage,
                                 article: @article,
                                 message: @message,
                                 editor_token: @editor_token
  end

  def edit
    @translation = Translation.find(params[:id])
    @passage = @translation.passage
    @article = @translation.article
    @editor_token = SecureRandom.uuid
    @lang_code_of_translation = Lang.convert_number_to_code(@translation.lang_number)
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def update
    @translation = Translation.find(params[:id])
    @passage = @translation.passage
    @article = @passage.article
    @editor_token = params[:editor_token]
    @lang_code_of_translation = Lang.convert_number_to_code(@translation.lang_number)
    @translation.assign_attributes(translation_params)
    @translation.set_attributes
    @valid = @translation.valid?
    return if @valid == false

    # @translation.separate_text if params[:separateText].present?
    @translation.save
    @message = t('translations.updated_message')
    ActionCable.server.broadcast 'translation_modification_channel',
                                 html: render(partial: 'passages/translation',
                                              locals: {passage: @passage, translation: @translation}),
                                 translation: @translation,
                                 lang_code: @lang_code_of_translation,
                                 passage: @passage,
                                 article: @article,
                                 message: @message,
                                 editor_token: @editor_token
  end

  def destroy
    @translation = Translation.find(params[:id])
    @passage = @translation.passage
    @article = @passage.article
    @user = current_user
    return if @article.translation_elimination_permitted_by(@user) == false

    comment = params[:comment]
    ip = request.remote_ip
    request = @translation.create_elimination_request(@user, comment, ip)
    if @article.screen_translation_requests?(@user)
      @message = t('article_requests.elimination_request_submitted')
      request.notify_author_of_being_proposed
    else
      @translation.merge_with(request)
      @message = t('translations.destroyed_message')
      request.notify_article_changed_without_screening

      user_icon = ApplicationController.helpers.icon_for(request.user)
      ActionCable.server.broadcast 'translation_elimination_channel',
                                   html: render(partial: 'passages/translation', locals: {passage: @passage}),
                                   translation: @translation,
                                   lang_code: @lang_code_of_translation,
                                   passage: @passage,
                                   article: @article,
                                   message: @message,
                                   user_name: (request.user.present? ? request.user.name : t('users.anonymous_user')),
                                   user_icon: user_icon,
                                   user_uid: (request.user.present? ? request.user.public_uid : request.ip)
    end
  end

  def new_title
    @article = Article.find_param(params[:article_uid])
    @translation = @article.translations.build
    @editor_token = SecureRandom.uuid
    @lang_code_of_translation = params[:lang_code_of_translation]
    source = Lang.convert_number_to_code(@article.lang_number)
    target = @lang_code_of_translation
    if source.present? && target.present?
      # youtubeの動画に翻訳データがあるなら、そちらを優先して表示する。なかったら機械翻訳を表示する。
      @translation_text = Youtube.get_translated_title(@article.reference_url, target) if @article.video?
      @translation_text = Lang.google_translate(source, target, @article.title) if @translation_text.blank?
    end
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def create_title
    @translation = Translation.new(translation_params)
    @article = @translation.article
    @translation.set_attributes
    @editor_token = params[:editor_token]
    @lang_code_of_translation = params[:lang_code_of_translation]
    @valid = @translation.valid?
    return if @valid == false

    @translation.save
    @message = t('translations.created_message')
    ActionCable.server.broadcast 'translation_modification_channel',
                                 html: render(partial: 'translations/title_translation',
                                              locals: { article: @article, translation: @translation }),
                                 translation: @translation,
                                 lang_code: @lang_code_of_translation,
                                 passage: nil,
                                 article: @article,
                                 message: @message,
                                 editor_token: @editor_token
  end

  def edit_title
    @translation = Translation.find(params[:id])
    @article = @translation.article
    @editor_token = SecureRandom.uuid
    @lang_code_of_translation = Lang.convert_number_to_code(@translation.lang_number)
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def update_title
    @translation = Translation.find(params[:id])
    @article = @translation.article
    @editor_token = params[:editor_token]
    @lang_code_of_translation = params[:lang_code_of_translation]
    @translation.assign_attributes(translation_params)
    @translation.set_attributes
    @valid = @translation.valid?
    return if @valid == false

    @translation.save
    @message = t('translations.updated_message')
    ActionCable.server.broadcast 'translation_modification_channel',
                                 html: render(partial: 'translations/title_translation',
                                              locals: {article: @article, translation: @translation}),
                                 translation: @translation,
                                 lang_code: @lang_code_of_translation,
                                 passage: nil,
                                 article: @article,
                                 message: @message,
                                 editor_token: @editor_token
  end

  def destroy_title
    @translation = Translation.find(params[:id])
    @translation_id = @translation.id
    @article = @translation.article
    @editor_token = params[:editor_token]
    @lang_code_of_translation = params[:lang_code_of_translation]
    @translation.destroy
    @message = t('translations.destroyed_message')
    ActionCable.server.broadcast 'translation_elimination_channel',
                                 html: render(partial: 'translations/title_translation',
                                              locals: { article: @article, translation: nil }),
                                 lang_code: @lang_code_of_translation,
                                 translation: nil,
                                 passage: nil,
                                 article: @article,
                                 message: @message,
                                 editor_token: @editor_token
  end

  def cancel
    @article = (Article.find(params[:article_id]) if params[:article_id].present?)
    @passage = (Passage.find(params[:passage_id]) if params[:passage_id].present?)
    @translation = (Translation.find(params[:translation_id]) if params[:translation_id].present?)
    @editor_token = params[:editor_token]
    @lang_code_of_translation = params[:lang_code_of_translation]
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end


  private

  def translation_params
    params.require(:translation).permit(:id, :_destroy, :article_id, :passage_id, :text, :lang_number)
  end


end

app/views/translations/_adding_title_translation_btn.html.erb
<%= form_with url: new_title_translations_path, method: :get do |f| %>
  <%= f.hidden_field :article_id, value: article.id %>
  <%= button_tag type: 'submit', class: 'btn btn-sm btn-gray-article py-2 font-weight-bold loading-show-btn mb-3' do %>
    <!--
    <i class="fas fa-plus mr-2"></i><#%= t 'translations.translate_title' %>
    -->
    <i class="far fa-language mr-2"></i><%= t 'translations.translate_title' %>
  <% end %>

  <div class="loading is-hide">
    <div class="loading_icon"></div>
  </div>

<% end %>

app/views/translations/_edit_btn.html.erb
<%= form_with model: translation, url: edit_translation_path(translation), method: :get, class: 'ml-2 d-inline' do |f| %>
  <%= button_tag type: 'submit', class: 'btn btn-sm btn-gray-article loading-show-btn rounded-circle',
                 style: "min-width:34px;min-height: 34px;" do %>
    <span class="far fa-pen"></span>
  <% end %>
  <div class="loading is-hide">
    <div class="loading_icon"></div>
  </div>
<% end %>

app/views/translations/_edit_form.html.erb
<!--  -->
<div class="mt-3 mb-5 translation-edit-form" id="passage-<%= passage.id %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= editor_token %>">
  <!--  -->
  <div id="passage-<%= passage.id %>-translation-lang-<%= @lang_code_of_translation %>-feedback-wrapper">
    <!-- Cancel button -->
    <div class="text-right">
      <%= form_with url: cancel_translations_path, method: :get do %>
        <%= hidden_field_tag :editor_token, editor_token %>
        <%= hidden_field_tag :lang_code_of_translation, @lang_code_of_translation %>
        <%= hidden_field_tag :passage_id, passage.id %>
        <%= hidden_field_tag :translation_id, translation.id %>
        <%= button_tag type: 'submit', class: 'btn btn-sm btn-gray-article py-2 loading-show-btn' do %>
          <i class="far fa-times mr-2"></i><%= t('articles.cancel') %>
        <% end %>
        <div class="loading is-hide">
          <div class="loading_icon"></div>
        </div>
      <% end %>
    </div>


    <h4 class="text-success my-3 font-weight-bold">
      <i class="fas fa-pen mr-2"></i><%= t 'translations.modify_translation' %></h4>

    <!-- Update button -->
    <%= form_with model: translation do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= hidden_field_tag :editor_token, editor_token %>
      <%= hidden_field_tag :lang_code_of_translation, @lang_code_of_translation %>

      <div class="text-preview-wrapper mb-3">
        <%= f.text_area :text, class: 'form-control preview-target-text', placeholder: t('translations.text_placeholder') , rows: 3 %>
        <%= render 'translations/lang_number_form', f: f, lang_number: f.object.lang_number %>
        <div class="small text-left">
          <a href="#" class="text-success text-preview-btn"><u><%= t('articles.text_preview') %></u></a></div>
      </div>

      <!--
      <#%= render 'articles/separate_text_form', f: f %>
      -->

      <!--
      <button class="btn btn-sm btn-border-gray w-100 mt-2 mb-4" type="button" data-toggle="collapse" data-target="#collapse-translation-<#%= translation.id %>" aria-expanded="false" aria-controls="collapseExample">
        <i class="far fa-comment-alt-lines"></i><#%= t('translations.write_comments') %>
      </button>
      <div class="collapse" id="collapse-translation-<#%= translation.id %>">
        <#%= text_area_tag :comment, "", {class: 'form-control', placeholder: t('translations.comments_placeholder'), rows: 4} %>
      </div>
      -->

      <%= button_tag type: 'submit', class: 'btn btn-solid loading-show-btn mt-4 w-100' do %>
        <%= t('translations.update') %>
      <% end %>

      <div class="loading is-hide">
        <div class="loading_icon"></div>
      </div>
    <% end %>




    <div class="text-right">
      <div class="form-deletion-btn need-one-or-more btn btn-sm btn-danger font-weight-bold" data-toggle="modal" data-target="#destroy-translation-<%= translation.id %>">
        <i class="fas fa-trash-alt mr-2"></i><%= t('translations.destroy') %>
      </div>
    </div>


    <!-- Modal -->
    <div class="modal fade" id="destroy-translation-<%= translation.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title font-weight-bold" id="exampleModalLabel"><%= t('translations.confirmation') %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <%= form_with model: translation, url: destroy_title_translation_path, method: :delete do %>
            <%= hidden_field_tag :editor_token, editor_token %>
            <%= hidden_field_tag :lang_code_of_translation, @lang_code_of_translation %>
            <div class="modal-body">
              <p><%= t('translations.confirmation_text') %></p>
              <!--
              <#%= text_area_tag :comment, "", {class: 'form-control', placeholder: t('translations.comments_placeholder'), rows: 4} %>
              -->
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('articles.cancel') %></button>

              <%= button_tag type: 'submit', class: 'btn btn btn-danger loading-show-btn' do %>
                <i class="fas fa-trash-alt mr-2"></i><%= t('translations.destroy') %>
              <% end %>

              <div class="loading is-hide">
                <div class="loading_icon"></div>
              </div>

            </div>
          <% end %>
        </div>
      </div>
    </div>

    <!-- 他のユーザーによる更新をリアルタイムで伝えるテキスト。 -->
    <div class="feedback-message my-3 small text-success"></div>
  </div>
</div>

app/views/translations/_lang_form.html.erb
<%= f.hidden_field :lang_number, value: lang_number, class: 'form-control preview-target-lang-number' %>
<fieldset disabled>
  <div class="form-group my-3">
    <select id="disabledSelect" class="form-control form-control-sm">
      <option><%= lang_number_to_lang_name(lang_number) %></option>
    </select>
  </div>
</fieldset>

app/views/translations/_new_btn.html.erb
<!-- 「翻訳を追加するボタン（translations#new）」 -->
<%= form_with url: new_translation_path, method: :get do |f| %>
  <%= f.hidden_field :passage_id, value: passage.id %>
  <%= f.hidden_field :lang_code_of_translation, value: @lang_code_of_translation %>

  <%= button_tag type: 'submit', class: 'btn btn-sm btn-gray-article float-left mr-2 loading-show-btn', id: "passage-#{passage.id}-translation-btn" do %>
    <i class="far fa-language"></i>
  <% end %>
  <div class="loading is-hide">
    <div class="loading_icon"></div>
  </div>
<% end %>

app/views/translations/_new_translation_btn.html.erb
<!-- 「翻訳を追加するボタン（translations#new）」 -->
<%= form_with url: new_translation_path, method: :get do |f| %>
  <%= f.hidden_field :passage_id, value: passage.id %>
  <%= f.hidden_field :lang_code_of_translation, value: @lang_code_of_translation %>

  <%= button_tag type: 'submit', class: 'btn btn-sm btn-gray-article float-left mr-2 loading-show-btn', id: "passage-#{passage.id}-translation-btn" do %>
    <i class="far fa-language"></i>
  <% end %>
  <div class="loading is-hide">
    <div class="loading_icon"></div>
  </div>
<% end %>

app/views/translations/_title_new_form.html.erb
<div class="mt-3 mb-5" id="article-title-<%= article.public_uid %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= editor_token %>">
  <div id="article-title-<%= article.public_uid %>-translation-lang-<%= @lang_code_of_translation %>-feedback-wrapper">
    <!-- Cancel button -->
    <div class="text-right">
      <%= form_with url: cancel_translations_path, method: :get do %>
        <%= hidden_field_tag :editor_token, editor_token %>
        <%= hidden_field_tag :lang_code_of_translation, @lang_code_of_translation %>
        <%= hidden_field_tag :article_id, article.id %>
        <%= hidden_field_tag :translation_id, nil %>
        <%= button_tag type: 'submit', class: 'btn btn-sm btn-gray-article py-2 loading-show-btn' do %>
          <i class="far fa-times mr-2"></i><%= t('articles.cancel') %>
        <% end %>
        <div class="loading is-hide">
          <div class="loading_icon"></div>
        </div>
      <% end %>
    </div>


    <h4 class="text-success my-3 font-weight-bold">
      <i class="fas fa-pen mr-2"></i><%= t('translations.add_title_translation') %></h4>

    <!-- Update button -->
    <%= form_with model: translation, url: create_title_translations_path, method: :post do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= hidden_field_tag :editor_token, editor_token %>
      <%= hidden_field_tag :lang_code_of_translation, @lang_code_of_translation %>

      <%= f.hidden_field :article_id, value: article.id %>
      <div class="text-preview-wrapper mb-3">
        <%= f.text_field :text, value: @translation_text, class: 'form-control form-control-lg preview-target-text', placeholder: t('translations.text_placeholder') %>
        <%= render 'translations/lang_number_form', f: f, lang_number: Lang.convert_code_to_number(@lang_code_of_translation) %>
        <div class="small text-left">
          <a href="#" class="text-success text-preview-btn"><u><%= t('articles.text_preview') %></u></a></div>
      </div>


      <%= button_tag type: 'submit', class: 'btn btn-solid loading-show-btn mt-4 w-100' do %>
        <%= t('translations.create') %>
      <% end %>

      <div class="loading is-hide">
        <div class="loading_icon"></div>
      </div>
    <% end %>


    <!-- 他のユーザーによる更新をリアルタイムで伝える。 -->
    <div class="feedback-message my-3 small text-success"></div>
  </div>
</div>

app/views/translations/cancel.js.erb
<% if @article.present?  %>
// タイトルの翻訳の編集（translations#new_title,edit_title）のキャンセル
$('#article-title-<%= @article.public_uid %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= @editor_token %>')
    .replaceWith("<%= j(render 'translations/title_translation', article: @article, translation: @translation) %>");

<% elsif @passage.present?  %>
// 翻訳の作成・編集（translations#new,edit）のキャンセル
$("#passage-<%= @passage.id %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= @editor_token %>")
    .replaceWith("<%= j(render 'passages/translation', translation: @translation, passage: @passage) %>");
<% end %>

app/views/translations/create.js.erb
<% if @valid == false %>
$('#passage-<%= @passage.id %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= @editor_token %>')
    .replaceWith("<%= j(render 'translations/new_form', translation: @translation, passage: @passage, editor_token: @editor_token ) %>");
<% end %>

app/views/translations/create_title.js.erb
<% if @valid == false %>
$('#article-title-<%= @article.public_uid %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= @editor_token  %>')
    .replaceWith("<%= j(render 'translations/title_new_form', translation: @translation, article: @article, editor_token: @editor_token ) %>");
<% end %>

app/views/translations/edit.js.erb
var $translation = $('#passage-<%= @passage.id %>-translation-lang-<%= @lang_code_of_translation %>');
var position = $translation.offset().top;
$('html, body').animate({scrollTop: position}, 300);
$translation
    .replaceWith("<%= j(render 'translations/edit_form', translation: @translation, passage: @passage, editor_token: @editor_token ) %>");

app/views/translations/new.js.erb
var $translation = $('#passage-<%= @passage.id %>-translation-lang-<%= @lang_code_of_translation %>');
var position = $translation.offset().top;
$('html, body').animate({scrollTop: position}, 300);
$translation
    .replaceWith("<%= j(render 'translations/new_form', translation: @translation, passage: @passage, editor_token: @editor_token ) %>");

app/views/translations/update.js.erb
<% if @valid == false %>
$('#passage-<%= @passage.id %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= @editor_token %>')
    .replaceWith("<%= j(render 'translations/edit_form', translation: @translation, passage: @passage, editor_token: @editor_token ) %>");
<% end %>

app/views/translations/update_title.js.erb
<% if @valid == false %>
$('#article-title-<%= @article.public_uid %>-translation-lang-<%= @lang_code_of_translation %>-edit-form-uid-<%= @editor_token  %>')
    .replaceWith("<%= j(render 'translations/title_edit_form', translation: @translation, article: @article, editor_token: @editor_token ) %>");

<% end %>