config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    get 'transcriber', to: 'static_pages#transcriber'
    get 'caption_downloader', to: 'static_pages#caption_downloader'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'
    get '/preview', to: 'static_pages#preview'
    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'


    # sitemap
    get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/diqtsub_sitemaps/sitemap.xml.gz')
    get 'ads.txt', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/ads.txt')

    resources :subtitles do
      collection do
        get  :select_captions
        post :download_caption
        get  :form_to_transcribe
        get  :checkout
        get  :transcribe
      end
    end

    #resources :wordnet do
    #  collection do
    #    get :home, :en_en_dict, :ja_ja_dict
    #  end
    #end
    #
    # 記事
    resources :articles do
      member do
        get :new_translation
        get :edit_title
        patch :update_title
        get :cancel
        get :translation_select
        # タグの編集
        get   :edit_tags
        patch :update_tags
        # 字幕のダウンロード
        get :caption_downloader
        get :download_caption
        # 翻訳
        post :batch_translation
        post :translate_in_bulk
        # 翻訳に課金する場合は以下
        get :checkout_translation
        get :success_translation
        # Youtubeから原文と翻訳をインポートする
        post :passage_importer
        post :import_passages
        post :translation_importer
        post :import_translations
        # SRTから原文と翻訳をインポートする。
        post :passage_file_importer
        post :import_passage_file
        post :translation_file_importer
        post :import_translation_file
      end
      collection do
        get  :new_video
        post :create_video
      end
    end


    resources :passages do
      member do
        # get :histories
      end
      collection do
        get :cancel
      end
    end

    # 翻訳 / 記事＆原文＆翻訳の投稿は実験のためにログイン不要にしても良い。問題が起きたら対処する。
    resources :translations do
      collection do
        get  :new_title
        post :create_title
        get :cancel
      end
      member do
        get    :edit_title
        patch  :update_title
        delete :destroy_title
      end
    end

    resources :tags, only: [:index, :show, :destroy] do
      collection do
        get :article_tags
      end
      member do
        get :articles
      end
    end

    resources :words, only: [:index] do
      collection do
        get :click_search
      end
    end


  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find_param(params[:id])
    @related_articles = @article.find_related_tags.limit(6)
    @title_translation = @article.find_title_translation(@lang_number_of_translation)
    @passages = @article.passages.order(start_time: :asc)
    @video_id = Youtube.get_video_id(@article.reference_url)
    @translated_lang_numbers = @article.translations.group(:lang_number).count.keys
    # metatagの@alternate設定
    @alternate = @translated_lang_numbers.unshift(@article.lang_number).uniq
                     .map { |number| {Lang.convert_number_to_code(number) => article_url(@article, locale: Lang.convert_number_to_code(number))} }
    @breadcrumb_hash = {t('articles.articles') => root_path,
                        @article.title => ''}
  end

  def new
    @article = Article.new
  end

  #def create
  #  @user = current_user
  #  @article = current_user.articles.build(article_params)
  #  @article.set_attributes_for_create
  #  @article.chapter = @chapter if @chapter.present?
  #  @article.separate_all_text if @article.valid?

  #  if @article.save_and_create_addition_request(request.remote_ip)
  #    @article.notify_subscribers_of_posting
  #    flash[:success] = t('articles.article_created')
  #    redirect_to @article
  #  else
  #    flash[:danger] = t('articles.article_failed_to_create')
  #    render 'articles/new'
  #  end
  #end

  def new_video
    @article = Article.new(reference_url: params[:article][:reference_url])
    @is_youtube_url = Youtube.youtube_url?(@article.reference_url)
    return if @is_youtube_url == false

    if (@predecessor = Article.find_by(youtube_id: Youtube.get_video_id(@article.reference_url)))
      flash[:warning] = t('articles.the_article_already_exists')
      return
    end

    # DATA APIへの接続を節約するためにsnippetで取得できる情報をここですべて取得しておく。
    snippet = Youtube.get_snippet(@article.reference_url)
    @article.title = Youtube.get_title(snippet)
    @article.scraped_image = Youtube.get_thumbnail(snippet)
    @tags = Youtube.get_tags(snippet)
    # タイトルの言語
    lang_code_of_title = Youtube.get_default_language(snippet)
    @article.lang_number = Lang.convert_code_to_number(lang_code_of_title)
    # 音声の言語
    @audio_lang = Youtube.get_default_audio_language(snippet)
    @article.lang_number_of_audio = Lang.convert_code_to_number(@audio_lang)
    # まれにAPI側に言語が設定されていない場合があるので、自前でも設定する。
    @article.set_lang_number
    # APIからタイトルとサムネを取得できなかった場合はmetainscpectorを使ってスクレイピングする。
    @article.scrape_youtube_url if @article.title.blank? || @article.scraped_image.blank?
    # @article.set_attributes_for_create
    @sub_lang_list = Youtube.importable_sub_lang_list(@article.reference_url)

    # 手動字幕がないか、手動字幕にオーディオ言語の字幕がない場合、自動字幕をデフォルトのインポート対象にする。
    if @sub_lang_list[:manual_sub_codes].blank? || @sub_lang_list[:manual_sub_codes].exclude?(@audio_lang)
      @audio_lang = "auto-#{@audio_lang}"
    end

    # セレクトフォームに渡すValueを設定する。
    if @sub_lang_list[:lang_codes].present?
      @sub_lang_codes = @sub_lang_list[:lang_codes]
      @sub_lang_codes.push(nil)
    else
      @sub_lang_codes = [nil]
      @audio_lang = nil
    end

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def create_video
    @article = Article.new(article_params)
    @article.video = true
    @user_uid = SecureRandom.uuid
    @article.set_attributes_for_create
    # @article.separate_all_text if @article.valid?
    if @article.save
      flash[:success] = t('articles.creating_video_succeeded')
      @article_uid = @article.public_uid
    else
      flash[:danger] = t('articles.creating_video_failed')
      redirect_to new_video_articles_url
    end

    lang_value = params[:article][:sub_lang_code]

    # 自動字幕読み込み
    if lang_value.include?('auto-')
      # 自動字幕の言語コード
      lang_code = Lang.convert_value_to_code(lang_value)
      # 自動字幕では、lang_valueとしてlang_codeを渡す。
      PassageCreationWorker.perform_async(@article_uid, 'auto-generated', lang_code, @locale, @user_uid)
    elsif lang_value.present?
      #lang_code = params[:article][:sub_lang_code]
      #return @error = 'Language unsupported' if Lang.lang_code_unsupported?(lang_code)
      PassageCreationWorker.perform_async(@article_uid, 'manual-sub', lang_value, @locale, @user_uid)
    else
      # ユーザーが取り込む字幕に「なし」を選んだ場合。
      @error = "not to import any caption"
    end

    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end


  def edit
    @article = Article.find_param(params[:id])
  end

  def update
    @article = Article.find_param(params[:id])
    @article.assign_attributes(article_params)
    # start_time_minutesとstart_time_secondsをまとめて秒換算する。
    @article.set_start_time

    if @article.save
      flash[:success] = t('articles.update_succeeded')
      redirect_to @article
    else
      flash[:success] = t('articles.update_failed')
      render 'articles/edit'
    end
  end

  def edit_title
    @article = Article.find_param(params[:id])
    @editor_token = SecureRandom.uuid
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def update_title
    @article = Article.find_param(params[:id])
    @editor_token = params[:editor_token]
    @article.assign_attributes(article_params)
    @article.set_lang_number
    @valid = @article.valid?
    return if @valid == false

    @article.save
    @message = t('articles.title_updated')
    # 画像の縦横比を保存する。
    # @article.update_width_and_height_of_image
    # user_icon = ApplicationController.helpers.icon_for(request.user)
    ActionCable.server.broadcast 'title_modification_channel',
                                 html: render(partial: 'articles/article_title', locals: {article: @article}),
                                 article: @article,
                                 message: @message,
                                 editor_token: @editor_token
  end

  def cancel
    @article = Article.find_param(params[:id])
    @editor_token = params[:editor_token]
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  # モバイルでの翻訳切り替えボタン
  def translation_select
    @article = Article.find_param(params[:id])
    @translated_lang_numbers = @article.translations.group(:lang_number).count.keys
    @lang_code_of_translation = params[:lang_code_of_translation]
    @is_original = request.referer[/sub=(.+)/, 1].blank?
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def edit_tags
    @article = Article.find_param(params[:id])
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def update_tags
    @article = Article.find_param(params[:id])
    @article.tag_list = params[:article][:tag_list]
    @article.save
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def destroy
    @article = Article.find_param(params[:id])
    @chapter = @article&.chapter
    @article.destroy
    flash[:success] = '記事を削除しました。'
    if @chapter.present?
      redirect_to chapter_url(@chapter)
    else
      redirect_to root_url
    end
  end

  def caption_downloader
    @article = Article.find_param(params[:id])
    @available_captions = @article.translations.group(:lang_number).count.keys
                              .map { |number| Lang.convert_number_to_code(number) }
    @available_captions.unshift('original')
    @lang_code_of_translation = params[:lang_code_of_translation]
    @value = if request.referer.present? && request.referer[/sub=(.+)/, 1].blank?
               'original'
             else
               @lang_code_of_translation
             end
    respond_to do |format|
      format.html { redirect_to @article }
      format.js
    end
  end

  def download_caption
    @article = Article.find_param(params[:id])
    caption = params[:article][:caption]
    if caption == 'original'
      data = @article.create_subtitles_srt
      file_name = @article.title
    else
      lang_number = Lang.convert_code_to_number(caption)
      data = @article.create_translations_srt(lang_number)
      file_name = if (title = @article&.find_title_translation(lang_number))
                    title.text
                  else
                    "#{@article.title}_#{Lang.convert_number_to_code(lang_number)}"
                  end
    end
    send_data(data, filename: "#{file_name}.srt")
  end

  def download_subtitles
    data = @article.create_subtitles_srt
    file_name = @article.title
    send_data(data, filename: "#{file_name}.srt")
  end

  def download_translations
    lang_number = params[:download_lang_number].to_i
    data = @article.create_translations_srt(lang_number)
    file_name = if @article&.find_title_translation(lang_number).present?
                  @article.find_title_translation(lang_number)
                else
                  "#{@article.title}_#{Lang.convert_number_to_code(lang_number)}"
                end
    send_data(data, filename: "#{file_name}.srt")
  end

  def batch_translation
    @article = Article.find_param(params[:id])
    @article_uid = @article.public_uid

    # refererからsubを取ってくる必要があるので、@lagn_of_translationは使えない。
    @trans_lang = request.referer[/sub=(.+)/, 1].presence
    @trans_lang_number = Lang.convert_code_to_number(@trans_lang)
    @lang_array = ApplicationController.helpers.lang_form_array

    @deepl_supported = Lang.deepl_supported_languages.include?(@lang_code_of_translation)
    # @characters_count = @article.characters_count
    # @amount = @article.translation_fee

    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.js
    end
  end

  def translate_in_bulk
    @article = Article.find_param(params[:id])
    @article_uid = @article.public_uid
    @user_uid = SecureRandom.uuid
    lang_number = params[:article][:lang_number_of_translation].to_i

app/views/articles/_batch_translation_modal.html.erb
<div class="badge-modal-wrapper" id="batch-translation-modal">
  <div class="overlay close-batch-translation-modal">

    <div class="close-btn">
      <i class="fal fa-times"></i>
    </div>

  </div>
  <div class="modal-booqs" id="batch-translation">

    <h3 class="font-weight-bold mt-3 mb-4"><i class="far fa-language mr-2"></i><%= t('articles.batch_translation') %></h3>
    <p class="text-secondary"><%= t('articles.explanation_about_batch_translation') %></p>
    <p class="text-danger"><%= t('articles.warning_to_edit_all_translations') %></p>

    <%= form_with model: @article, url: translate_in_bulk_article_path(@article), method: :post do |f| %>

      <div class="card my-3">
        <div class="card-body">
          <%= f.select :lang_number_of_translation, options_for_select(lang_form_array, @lang_number_of_translation), {},
                       { class: 'form-control form-control mb-3' } %>
          <div class="form-check form-check-inline text-left mb-4">
            <%= radio_button_tag :type_of_translator, 'deepl', true, class: 'form-check-input', id: "deepl-translator" %>
            <label class="form-check-label ml-1 mr-3" for="deepl-translator">DeepL翻訳</label>
            <%= radio_button_tag :type_of_translator, 'google', false, class: 'form-check-input', id: "google-translator" %>
            <label class="form-check-label ml-1 mr-3" for="google-translator">Google翻訳</label>
          </div>

          <!--
          <p class="text-secondary">文字数：<#%= @characters_count %></p>
          <p class="text-secondary mb-1">料金：<b><#%= @amount %>円</b></p>
          -->

        </div>
      </div>

      <%= f.submit t('articles.execute'), class: 'btn btn-solid w-100 mt-5 loading-show-btn' %>
      <div class="loading is-hide">
        <div class="loading_icon"></div>
      </div>
    <% end %>




    <!-- 課金する場合 -->
    <!--
    <h3 class="green my-3"><i class="far fa-language"></i>一括で翻訳する</h3>
    <p class="text-secondary text-left">原文をすべて自動で翻訳します。</p>

    <p class="text-secondary text-left">翻訳には、１万文字まで100円、その後は１万文字ごとに100円の追加料金がかかります。</p>
    -->


    <!-- 埋め込みのstripe.jsがきちんと機能するようにturbolinksを切る -->
    <!--
    <div data-turbolinks='false'>
      <#%= form_with model: @article, url: checkout_translation_article_path(@article), method: :get, local: true do |f| %>
        <#%= hidden_field_tag :sub, request.referer[/sub=(.+)/, 1] %>

        <div class="card">
          <div class="card-body">
            <#%= f.select :lang_number_of_translation, options_for_select(@lang_array, @trans_lang_number), {},
                         {class: 'form-control form-control mb-3'} %>
            <div class="form-check form-check-inline text-left mb-4">
              <#%= radio_button_tag :type_of_translator, 'deepl', true, class: 'form-check-input', id: "deepl-translator" %>
              <label class="form-check-label ml-1 mr-3" for="deepl-translator">DeepL翻訳</label>
              <#%= radio_button_tag :type_of_translator, 'google', false, class: 'form-check-input', id: "google-translator" %>
              <label class="form-check-label ml-1 mr-3" for="google-translator">Google翻訳</label>
            </div>

            <p class="text-secondary">文字数：<#%= @characters_count %></p>
            <p class="text-secondary mb-1">料金：<b><#%= @amount %>円</b></p>

          </div>
        </div>

        <#%= f.submit "一括で翻訳する", class: 'btn btn-solid w-100 mt-5 loading-show-btn' %>
        <div class="loading is-hide">
          <div class="loading_icon"></div>
        </div>
      <#% end %>
    </div>
    -->

  </div>

</div>

app/views/articles/_caption_downloader_modal.html.erb
<div class="badge-modal-wrapper" id="caption-downloader-modal">
  <div class="overlay close-caption-downloader-modal">

    <div class="close-btn">
      <i class="fal fa-times"></i>
    </div>

  </div>
  <div class="modal-booqs" id="caption-downloader">


    <h3 class="font-weight-bold my-3"><i class="far fa-download mr-2"></i><%= t 'articles.download_captions' %>
    </h3>

    <p><%= t('articles.explanation_of_download_captions') %></p>

    <% if @article.passages.present? %>
      <%= form_with model: @article, url: download_caption_article_path(@article), method: :get, local: true do |f| %>


        <%= f.select :caption, options_for_select(@available_captions.map { |code| caption_download_select_form_creator(code) }, @value),
                     {},
                     {class: 'form-control form-control my-3 w-100'} %>

        <%= button_tag type: 'submit', class: "btn btn-solid mt-4 w-100" do %>
          <%= t 'articles.download' %>
        <% end %>


      <% end %>

    <% else %>
      <p class="text-danger"><%= t 'subtitles.there_are_no_captions' %></p>
    <% end %>

  </div>
</div>

app/views/articles/_cards.html.erb
<!-- 参考：https://codepen.io/frontdevsdc/pen/yRPoYR -->
<div class="container">
  <div class="card-columns">
    <% articles.each do |article| %>
      <div class="card my-3">

        <a href="<%= article_url(article) %>">
          <img class="card-img-top" src="<%= article.scraped_image %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text small">
              <%= article.translated_title(@lang_number_of_locale) %>
            </p>
            <p class="card-text">
              <small class="text-muted"><i class="fas fa-video"></i><%= return_play_time(article.video_duration) %><i class="fas fa-volume-up"></i><%= t("lang.#{article.lang_code_of_audio}") %><br><i class="fas fa-eye"></i><%= article.view_count&.to_s(:delimited, delimiter: ',') %><%= t('articles.video_views') %></small></p>
          </div>
        </a>
      </div>
    <% end %>
    <!--
    <div class="card">
      <a href="#">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1472076638602-b1f8b1ac0b4a?ixlib=rb-0.3.5&s=63c9de7246b535be56c8eaff9b87dd89&auto=format&fit=crop&w=500&q=80" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, doloremque!</h5>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio iusto maxime nemo
            omnis praesentium similique.</p>
          <p class="card-text">
            <small class="text-muted"><i class="fas fa-eye"></i>1000<i class="far fa-user"></i>admin<i class="fas fa-calendar-alt"></i>Jan
              20, 2018</small></p>
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1535086181678-5a5c4d23aa7d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=34c86263bec2c8f74ceb74e9f4c5a5fc&auto=format&fit=crop&w=500&q=80" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Lorem ipsum dolor sit amet, consectetur.</h5>
          <p class="card-text">Amet commodi deleniti enim laboriosam odio placeat praesentium quis ratione rerum
            suscipit.</p>
          <p class="card-text">
            <small class="text-muted"><i class="fas fa-eye"></i>1000<i class="far fa-user"></i>admin<i class="fas fa-calendar-alt"></i>Jan
              20, 2018</small></p>
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1535074153497-b08c5aa9c236?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d2aaf944a59f16fe1fe72f5057b3a7dd&auto=format&fit=crop&w=500&q=80" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Lorem ipsum dolor sit amet, consectetur.</h5>
          <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional
            content. This content is a little bit longer.</p>
          <p class="card-text">
            <small class="text-muted"><i class="fas fa-eye"></i>1000<i class="far fa-user"></i>admin<i class="fas fa-calendar-alt"></i>Jan
              20, 2018</small></p>
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1535124406821-d2848dfbb25c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=98c434d75b44c9c23fc9df2a9a77d59f&auto=format&fit=crop&w=500&q=80" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Lorem ipsum dolor sit amet.</h5>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. At, consequatur culpa cumque
            deserunt dignissimos error explicabo fugiat harum ipsam magni minus mollitia nemo perferendis qui
            repellendus rerum saepe vel voluptate voluptatem voluptatum!
            Aperiam, labore, molestiae!..</p>
          <p class="card-text">
            <small class="text-muted"><i class="fas fa-eye"></i>1000<i class="far fa-user"></i>admin<i class="fas fa-calendar-alt"></i>Jan
              20, 2018</small></p>
        </div>
      </a>
    </div>
    <div class="card">
      <a href="#">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1508015926936-4eddcc6d4866?ixlib=rb-0.3.5&s=10b3a8717ab609be8d7786cab50c4e0b&auto=format&fit=crop&w=500&q=80" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h5>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque commodi debitis eaque
            explicabo fuga maiores necessitatibus, neque omnis optio vel!</p>
          <p class="card-text">
            <small class="text-muted"><i class="fas fa-eye"></i>1000<i class="far fa-user"></i>admin<i class="fas fa-calendar-alt"></i>Jan
              20, 2018</small></p>
        </div>
      </a>
    </div>
    -->


  </div>
</div>

app/views/articles/_new_video_form.html.erb
<h1 class="text-left font-weight-bold mb-5"><i class="far fa-video-plus mr-2"></i><%= t('chapters.create_video') %></h1>


<%= form_with model: article, url: create_video_articles_path, method: :post do |f| %>
  <div id="scraping-error-massages"></div>
  <%= f.hidden_field :reference_url, value: article&.reference_url %>
  <%= f.hidden_field :scraped_image, value: article&.scraped_image %>

  <%= image_tag article&.scraped_image, class: 'img-fluid w-25 mb-2' %>

  <h3 class="font-weight-bold my-3"><%= article.title %></h3>
  <%= f.hidden_field :title, value: article.title %>
  <!-- ユーザーの認知負荷削減のために、ここではタイトルは編集できないようにする。
  <#%= f.text_field :title, class: 'form-control form-control-lg font-weight-bold' %>
  -->


  <%= render "articles/lang_number_form", f: f %>

  <%= render "articles/lang_number_of_audio_form", f: f %>


  <div class="input-group mt-4 mb-2">
    <div class="input-group-prepend">
      <div class="input-group-text"><i class="far fa-tag mr-2"></i><%= t('tags.tags') %></div>
    </div>
    <%= f.text_area :tag_list, class: 'form-control', value: @tags&.join(','), placeholder: "タグを入力してください。", id: 'inlineFormInputGroup', rows: 3 %>
    <!--
    <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Username">
    -->
  </div>
  <div class="text-left">
    <span class="text-secondary small text-left"><%= t('articles.multiple_tags_setting') %></span>
  </div>

  <h4 class="text-left font-weight-bold mt-5 mb-4"><%= t 'articles.import_caption' %></h4>
  <p><%= t 'articles.please_select_transcript' %></p>


  <%= f.select :sub_lang_code, options_for_select(@sub_lang_codes.map { |code| caption_import_select_form_creator(code) }, @audio_lang),
               {},
               {class: 'form-control form-control my-3 w-100'} %>




  <%= button_tag type: 'submit', class: "btn btn-solid loading-show-btn mt-5 w-100" do %>
    <i class="far fa-edit"></i><%= t('chapters.create') %>
  <% end %>
  <div class="loading is-hide">
    <div class="loading_icon"></div>
  </div>

<% end %>

app/views/articles/_translation_file_importer_modal.html.erb
<div class="badge-modal-wrapper" id="translation-file-importer-modal">
  <div class="overlay close-translation-file-importer-modal">

    <div class="close-btn">
      <i class="fal fa-times"></i>
    </div>

  </div>
  <div class="modal-booqs" id="translation-file-importer">

    <h3 class="font-weight-bold mt-3 mb-4"><%= t 'articles.import_file' %></h3>
    <p class="text-left"><%= t('articles.you_can_import_srt_as_translations_html', path: caption_downloader_path) %></p>
    <% if @article.passages.present? %>
      <p class="text-danger"><%= t('articles.warning_to_edit_all_translations') %></p>
    <% end %>

    <%= form_with model: @article, url: import_translation_file_article_path(@article), method: :post do |f| %>


      <div class="custom-file">
        <%= f.file_field :file, class: 'custom-file-input', id: 'customFile' %>
        <label class="custom-file-label" for="customFile" data-browse="<%= t('articles.file_reference') %>"><%= t('articles.select_file') %></label>
      </div>

      <div class="input-group my-4">
        <div class="input-group-prepend">
          <label class="input-group-text" for="articleTitleLanguage"><%= t('articles.srt_lang') %></label>
        </div>
        <%= f.select :lang_number, options_for_select(lang_form_and_auto_configure, @lang_number_of_translation),
                     {},
                     {class: 'custom-select form-control', id: 'articleTitleLanguage'} %>
      </div>

      <%= f.submit t('articles.execute'), class: 'btn btn-solid d-block w-100 my-5 loading-show-btn' %>

      <div class="loading is-hide" id="loading">
        <div class="loading_icon"></div>
      </div>
    <% end %>


  </div>
</div>

app/views/articles/edit_tags.js.erb
$('.loading').addClass('is-hide');
$('#article-tags-<%= @article.public_uid %>').html("<%= j(render "articles/tag_form", article: @article) %>");

app/views/articles/edit_title.js.erb
$('#article-title-<%= @article.public_uid  %>').replaceWith("<%= j(render 'articles/title_edit_form', article: @article, editor_token: @editor_token) %>");
//var position = $('#article-title-<#%= @article.public_uid %>-edit-form-uid-<#%= @token %>').offset().top;
//$('html, body').animate({scrollTop: position}, 500);

app/views/articles/import_translation_file.js.erb
<% if @error.blank? %>
$('.loading').addClass('is-hide');
$('#translation-file-importer').html('<%= j(render 'shared/progress_bar', content_id: @article_uid, user_id: @user_uid) %>');

// 削除アイコンを消す＆モーダルを閉じられなくする
var $closeModal = $('.close-translation-file-importer-modal');
$closeModal.html('');
$closeModal.off();


<% else %>

var articlePath = "<%= article_path(@article)%>";
window.location.href = articlePath;

<% end %>