config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'static_pages#home'
    get 'transcriber', to: 'static_pages#transcriber'
    get 'caption_downloader', to: 'static_pages#caption_downloader'
    post '/create-checkout-session', to: 'static_pages#create-checkout-session'
    get '/preview', to: 'static_pages#preview'
    mount Sidekiq::Web => '/sidekiq'
    mount ActionCable.server => '/cable'

    # APIとサービスの「認証情報」の設定
    get '/auth/google_oauth2/callback', to: 'static_pages#home'


    # sitemap
    get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/diqtsub_sitemaps/sitemap.xml.gz')
    get 'ads.txt', to: redirect('https://s3-ap-northeast-1.amazonaws.com/kawanji/ads.txt')

    resources :subtitles do
      collection do
        get  :select_captions
        post :download_caption
        get  :form_to_transcribe
        get  :checkout
        get  :transcribe
      end
    end

    #resources :wordnet do
    #  collection do
    #    get :home, :en_en_dict, :ja_ja_dict
    #  end
    #end
    #
    # 記事
    resources :articles do
      member do
        get :new_translation
        get :edit_title
        patch :update_title
        get :cancel
        get :translation_select
        # タグの編集
        get   :edit_tags
        patch :update_tags
        # 字幕のダウンロード
        get :caption_downloader
        get :download_caption
        # 翻訳
        post :batch_translation
        post :translate_in_bulk
        # 翻訳に課金する場合は以下
        get :checkout_translation
        get :success_translation
        # Youtubeから原文と翻訳をインポートする
        post :passage_importer
        post :import_passages
        post :translation_importer
        post :import_translations
        # SRTから原文と翻訳をインポートする。
        post :passage_file_importer
        post :import_passage_file
        post :translation_file_importer
        post :import_translation_file
      end
      collection do
        get  :new_video
        post :create_video
      end
    end


    resources :passages do
      member do
        # get :histories
      end
      collection do
        get :cancel
      end
    end

    # 翻訳 / 記事＆原文＆翻訳の投稿は実験のためにログイン不要にしても良い。問題が起きたら対処する。
    resources :translations do
      collection do
        get  :new_title
        post :create_title
        get :cancel
      end
      member do
        get    :edit_title
        patch  :update_title
        delete :destroy_title
      end
    end

    resources :tags, only: [:index, :show, :destroy] do
      collection do
        get :article_tags
      end
      member do
        get :articles
      end
    end

    resources :words, only: [:index] do
      collection do
        get :click_search
      end
    end


  end
end

app/views/layouts/_breadcrumb.html.erb
<% if items_hash.present? %>
  <nav aria-label="breadcrumb" class="mx-auto" style="max-width: 1140px;">

    <ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">

      <% items_hash.each.with_index(1) do |(key, value), i| %>
        <% if value.present? %>

          <li class="breadcrumb-item" itemprop="itemListElement" itemscope
              itemtype="https://schema.org/ListItem">
            <a itemprop="item" href="<%= value %>">
              <span itemprop="name"><%= key %></span></a>
            <meta itemprop="position" content="<%= i %>"/>
          </li>

        <% else %>

          <li class="breadcrumb-item active" aria-current="page"
              itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
            <span itemprop="name"><%= key %></span>
            <meta itemprop="position" content="<%= i %>"/>
          </li>

        <% end %>


      <% end %>

    </ol>
  </nav>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer" style="margin-top: 200px;">

  <div class="container pt-4">
    <div class="row">
      <div class="col-xl-4 pl-3">
        <div class="my-3"><%= link_to 'DiQt', "https://www.booqs.net/#{@locale}",  target: '_blank', rel: 'noopener' %></div>
        <div class="my-3"><%= link_to 'iOS版DiQt', "https://tools.applemediaservices.com/app/1594559036?country=jp",  target: '_blank', rel: 'noopener' %></div>
        <div class="my-3"><%= link_to 'Android版DiQt', "https://play.google.com/store/apps/details?id=com.booqs.booqs_mobile",  target: '_blank', rel: 'noopener' %></div>
        <div class="my-3"><%= link_to 'Chrome拡張版DiQt', "https://chrome.google.com/webstore/detail/booqs-dictionary/khgjdchimekphdebkmcknjkphkbpbpkj?hl=#{@locale}",  target: '_blank', rel: 'noopener' %></div>
      </div>

      <div class="col-xl-4 pl-3">

        <div class="my-3"><%= link_to t('subtitles.download_captions_on_youtube'), caption_downloader_path %></div>
        <div class="my-3"><%= link_to t('subtitles.transcribe_videos_on_youtube'), caption_downloader_path %></div>
      </div>

      <div class="col-xl-4 pl-3">
        <div class="my-3"><%= link_to t('layouts.company'), "https://www.booqs.net/#{@locale}/about",  target: '_blank', rel: 'noopener' %></div>
        <div class="my-3"><%= link_to  t('layouts.contact'), "https://www.booqs.net/#{@locale}/contact", target: '_blank', rel: 'noopener' %></div>
        <div class="my-3"><%= link_to t('layouts.commercial_transaction_act'), "https://www.booqs.net/#{@locale}/legal" %></div>
        <div class="my-3"><%= link_to t('layouts.term_of_service'), "https://www.booqs.net/#{@locale}/terms_of_service" %></div>
        <div class="my-3"><%= link_to t('layouts.privacy_policy'), "https://www.booqs.net/#{@locale}/privacy_policy" %></div>
      </div>


    </div>

  </div>
</footer>

app/views/layouts/_google.html.erb
<% if Rails.env.production? %>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-20WHS8ME62"></script>
  <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-20WHS8ME62');
  </script>


  <!-- google adsense -->
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9489251797522277"
          crossorigin="anonymous"></script>
  <!-- footer 広告 -->
  <!--
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  -->
  <!-- google search console -->
  <!--
  <meta name="google-site-verification" content="FSoMz6MyTVTjgEaa9UJ5B1l6JxYxNc3ZBbOjN9mzlug" />
  -->

<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="container logo text-left pt-3 d-flex">

    <%= link_to root_path do %>
      <img src="<%= asset_url("BooQs_logo.svg") %>" class="mr-2"><span class="pt-2">DiQt Sub（β）</span>
    <% end %>

    <%= link_to new_article_path, class: 'ml-auto' do %>
      <div class="btn btn-sm btn-light-green font-weight-bold">
        <i class="far fa-video-plus mr-2"></i><%= t('articles.create') %>
      </div>
    <% end %>
  </div>
</header>


<% if @navbar_displayed %>
  <%= render 'layouts/navbar' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav id="nav-menu" class="mb-5">
  <ul class="nav-menu-inner container" style="min-width: 720px;">

    <li class="<%= "active" if request.path == root_path %>">
      <a href="<%= root_path %>">
        <i class="far fa-newspaper mr-2"></i><%= t('articles.articles') %>
      </a>
    </li>

    <li class="<%= "active" if request.path == tags_path %>">
      <a href="<%= tags_path %>">
        <i class="far fa-tags mr-2"></i><%= t('tags.tags') %>
      </a>
    </li>


    <li class="<%= "active" if request.path == articles_tag_path(48) %>">
      <a href="<%= articles_tag_path(48) %>">
        <i class="far fa-tags mr-2"></i>flutter
      </a>
    </li>


    <li class="<%= "active" if request.path == articles_tag_path(2) %>">
      <a href="<%= articles_tag_path(2) %>">
        <i class="far fa-tags mr-2"></i>hololive
      </a>
    </li>

    <li class="<%= "active" if request.path == caption_downloader_path %>">
      <a href="<%= caption_downloader_path %>">
        <i class="far fa-closed-captioning mr-2"></i><%= t('subtitles.caption_download') %>
      </a>
    </li>

    <li class="<%= "active" if request.path == transcriber_path %>">
      <a href="<%= transcriber_path %>">
        <i class="far fa-file-video mr-2"></i><%= t('subtitles.transcription') %>
      </a>
    </li>
  </ul>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<!-- Media Queriesが効かない問題の対応：　https://qiita.com/noraworld/items/10926dfa6c88f3afdbb3 -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

<!-- Bootstrap4のDropDownを動かすために導入した。参考：  https://johnnn.tech/q/rails-6-issue-with-bootstrap-5-dropdown/ -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-popRpmFF9JQgExhfw5tZT4I9/CI5e2QcuUZPOVXb1m7qUmeR2b50u+YFEYe1wgzy" crossorigin="anonymous"></script>
<!-- 無限スクロール -->
<script src="https://unpkg.com/infinite-scroll@4/dist/infinite-scroll.pkgd.min.js"></script>

app/views/layouts/_recommendation_to_switch_locale.html.erb
<% if @user_language.present? && @locale.to_s != @user_language %>

  <% case @user_language when 'ja' %>
    <div class="alert alert-info my-4 container text-center" role="alert">
      日本語バージョンがご利用いただけます。
      <%= link_to '/ja' do %>
        <div class="ml-3 btn btn btn-info font-weight-bold">日本語に切り替える</div>
      <% end %>
    </div>

  <% when 'en' %>
    <div class="ml-3 alert alert-info my-4 container text-center" role="alert">
      English version is available.
      <%= link_to '/en' do %>
        <div class="btn btn btn-info font-weight-bold">Switch to English</div>
      <% end %>
    </div>

  <% end %>



<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- Bing対策 参照：https://tek2tech.com/seo-for-multilingual-sites/ -->
<html lang="<%= @locale.to_s %>">
<head>
  <%= render 'layouts/google' %>
  <!-- http://vdeep.net/rubyonrails-meta-tags-seo -->
  <%= display_meta_tags(default_meta_tags) %>
  <%= yield :links %>
  <%= render "layouts/rails_default" %>
</head>

<body>
<!-- 一部ページでのturobolinksの無効化 / START  / 参考：　https://qiita.com/Jackson123/items/981d6362bcf9d2a136c3　-->
<div
  <% if content_for?(:body_attributes) %>
  <%= yield(:body_attributes) %>
  <% end %>
  >


  <%= render "layouts/header" %>


  <div class="main" id="main">

    <div class="feedback_message w-100 text-center">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    </div>
    <%= yield %>
  </div>

  <!-- 特定のボタンを押した時に表示されるloading -->
  <div class="loading is-hide" id="loading">
    <div class="loading_icon"></div>
  </div>


  <%= render 'layouts/footer' %>

</div>
<!-- Turbolinksの一部ページでの無効化 / END-->
</body>
</html>